outputDir: tmp/dryrun
logging:
  logLevel: debug
  logToConsole: false
  logOutputFile: tmp/log
advancedTypescriptSupport:
  enabled: false
sensitiveCodepaths:
  - "index.js"
allowedAuthors:
  usernames:
    - "joshcummingsdesign"
