name: dr action
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  
jobs:
  dryrun:
    name: dryrun
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v3
      - uses: dryrunsecurity/dryrunsec-action@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          dr_config: './.dryrunsecurity.yaml'
